### ISSUE TITLE
lsp-types 1.4 1.5 1.6 fail to build with GHC 9.8.1: `Duplicate record field ‘_foo’ in export list`

### ISSUE THREAD

**Issue by andreasabel** [haskell/lsp#530]
lsp-types-1.6.0.0 fails to build with GHC 9.8.1: `Duplicate record field ‘_foo’ in export list`
```
cabal get lsp-types-1.6.0.0
cd lsp-types-1.6.0.0
cabal build -w ghc-9.8.1
...
(tons of similar errors)
...
src/Language/LSP/Types.hs:45:5: error: [GHC-97219]
    Duplicate record field ‘_partialResultToken’ in export list:
       ‘module Language.LSP.Types.WorkspaceSymbol’ exports the field ‘_partialResultToken’
       belonging to the constructor ‘WorkspaceSymbolParams’
         imported from ‘Language.LSP.Types.WorkspaceSymbol’ at src/Language/LSP/Types.hs:92:1-51
       ‘module Language.LSP.Types.CallHierarchy’ exports the field ‘_partialResultToken’
       belonging to the constructor ‘CallHierarchyIncomingCallsParams’
         imported from ‘Language.LSP.Types.CallHierarchy’ at src/Language/LSP/Types.hs:49:1-49
       ‘module Language.LSP.Types.CallHierarchy’ exports the field ‘_partialResultToken’
       belonging to the constructor ‘CallHierarchyOutgoingCallsParams’
         imported from ‘Language.LSP.Types.CallHierarchy’ at src/Language/LSP/Types.hs:49:1-49
    Suggested fix: Perhaps you intended to use DuplicateRecordFields
   |
45 |   , module Language.LSP.Types.WorkspaceSymbol
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This is https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.8#re-exporting-clashing-record-fields-now-requires-xduplicaterecordfields

The immediate cure is to revise `lsp-types-1.6.0.0` to `base < 4.19`: https://hackage.haskell.org/package/lsp-types-1.6.0.0/revisions/

One could consider a patch release adding `DuplicateRecordFields` to the `default-extensions` to enable building `lsp-types-1.6.0.0` with GHC > 9.6.

**Comment by andreasabel** [comment]
Also revised lsp-types 1.4.0.1 and 1.5.0.0.

**Comment by andreasabel** [comment]
`agda-language-server` has been using lsp-1, but I will try to migrate it to lsp-2.

**Comment by andreasabel** [comment]
I notice `lsp-types-2` has ballooned into 400 modules, how come?  This makes compilation very slow.

**Comment by michaelpj** [comment]
`lsp-types-2` is now mostly auto-generated, so it's one module per type. There's no sensible way to group them and putting everything in one module would also be pretty bad. It goes much faster when you tell GHC it can use some parallelism building the package (I await the GHC/cabal semaphore work eagerly...), e.g. 

```
package lsp-types
  ghc-options: -j4
```

**Comment by michaelpj** [comment]
I think there isn't anything else to do here?

**Comment by andreasabel** [comment]
@michaelpj If you give me upload rights for lsp-types, I can make patch releases (which amounts to adding the extension to the cabal file(s)).

**Comment by michaelpj** [comment]
I can do that but I'm also happy to fix things. I thought we got everything - what else do you want to do?

**Comment by andreasabel** [comment]
What I meant was making lsp-1 available on GHC 9.8:

> One could consider a patch release adding `DuplicateRecordFields` to the `default-extensions` to enable building `lsp-types-1.6.0.0` with GHC > 9.6.

**Comment by michaelpj** [comment]
Ah, I see you already have it via the `haskell` org!
